import drinkMateImg from '../assets/drinkMate.png';
import fakeKeyboardImg from '../assets/fakeKeyboard.png';
import numberGuessImg from '../assets/numberGuess.png';
import todolistImg from '../assets/todolist.png';

export const projectData = [
  {
    id: 'numberGuess',
    imgUrl: numberGuessImg,
    title: 'Number Guess',
    summary: '간단한 숫자 맞추기 게임입니다.',
    desc: '1부터 9까지의 숫자 중 랜덤 숫자 3개를 맞추면 클리어 합니다.',
    period: '2024.05.10 - 2024.05.13',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows'] },
      { label: '라이브러리', item: [] },
      { label: '툴', item: ['Visual Studio Code', 'GitHub'] },
      { label: '서비스', item: ['GitHub Pages'] },
    ],
    demo: 'https://yeon7513.github.io/number-guess/',
    source: 'https://github.com/yeon7513/number-guess',
  },
  {
    id: 'typingRace',
    imgUrl: '',
    title: 'TYPING RACE',
    summary: '간단한 타이핑 게임입니다.',
    desc: '위에서 내려오는 단어를 빠르게 타이핑 해보세요!',
    period: '2024.05.26 - 2024.05.31',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows'] },
      { label: '라이브러리', item: [] },
      { label: '툴', item: ['Visual Studio Code', 'GitHub'] },
      { label: '서비스', item: ['GitHub Pages'] },
    ],
    demo: 'https://yeon7513.github.io/typing-race-js/',
    source: 'https://github.com/yeon7513/typing-race-js',
  },
  {
    id: 'drinkMate',
    imgUrl: drinkMateImg,
    title: 'Drink Mate',
    summary: '자판기 머신을 구현했습니다.',
    desc: '자판기 머신을 구현했습니다.',
    period: '2024.07.12 - 2024.07.15',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows'] },
      { label: '라이브러리', item: [] },
      { label: '툴', item: ['Visual Studio Code', 'GitHub'] },
      { label: '서비스', item: ['GitHub Pages'] },
    ],
    demo: 'https://yeon7513.github.io/vending-machine/',
    source: 'https://github.com/yeon7513/vending-machine',
  },
  {
    id: 'fakeKeyboard',
    imgUrl: fakeKeyboardImg,
    title: 'Fake Keyboard',
    summary: 'key event를 활용한 가상 키보드입니다.',
    desc: 'key event를 활용한 가상 키보드입니다.',
    period: '2024.05.21 - 2024.05.21',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows'] },
      { label: '라이브러리', item: [] },
      { label: '툴', item: ['Visual Studio Code', 'GitHub'] },
      { label: '서비스', item: ['GitHub Pages'] },
    ],
    demo: 'https://yeon7513.github.io/fake-keyboard/',
    source: 'https://github.com/yeon7513/fake-keyboard',
  },
  {
    id: 'todoList',
    imgUrl: todolistImg,
    title: 'TODOLIST',
    summary: 'CRUD를 구현한 TODOLIST입니다.',
    desc: '할 일과 할 시간을 생성하고, 수정 및 삭제가 가능합니다.',
    period: '2023.12.12 - 2023.12.14',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows', 'React JS'] },
      { label: '라이브러리', item: ['BootStrap'] },
      { label: '툴', item: ['Visual Studio Code', 'GitHub'] },
      { label: '서비스', item: ['Netlify'] },
    ],
    demo: 'https://my-todolist-yeon.netlify.app/',
    source: 'https://github.com/yeon7513/my-todolist',
  },
  {
    id: 'matchCard',
    imgUrl: '',
    title: "Let's Match Cards!",
    summary: '카드 짝 맞추기 게임입니다.',
    desc: '카드 짝 맞추기 게임입니다.',
    period: '2023.11.27. - 2023.12.12',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows', 'React JS'] },
      { label: '라이브러리', item: ['BootStrap'] },
      { label: '툴', item: ['Visual Studio Code', 'GitHub'] },
      { label: '서비스', item: ['Netlify'] },
    ],
    demo: 'https://lets-match-cards.netlify.app/',
    source: 'https://github.com/yeon7513/macth-cards',
  },
  {
    id: 'team_billishu',
    imgUrl: '',
    title: '[팀프로젝트] BILLISHU',
    summary: '공간 대여 서비스 플랫폼입니다.',
    desc: '공간 대여 서비스 플랫폼입니다.',
    period: '2024.06.12. - 2024.06.28.',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows'] },
      {
        label: '라이브러리',
        item: [
          'swiper',
          'BootStrap',
          '카카오 맵 API',
          'FullCalendar',
          'Google Calendar API',
        ],
      },
      { label: '툴', item: ['Visual Studio Code', 'GitHub'] },
      { label: '서비스', item: ['GitHub Pages'] },
    ],
    demo: 'https://goyangyee22.github.io/project/',
    source: 'https://github.com/goyangyee22/project',
  },
  {
    id: 'team_ifarm',
    imgUrl: '',
    title: '[팀프로젝트] 아이팜',
    summary: '스마트팩토리 어쩌구....',
    desc: '스마트팜',
    period: '2024.06.12. - 2024.06.28.',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows', 'React JS'] },
      {
        label: '라이브러리',
        item: [
          'material-ui',
          'd3.js',
          'Recharts',
          'swiper',
          '스마트팜 빅데이터 제공 서비스 API',
          '스마트팜 우수농가 공개 데이터 API',
          '작물 병해충 검색 서비스 API',
          'OpenWeather API',
          'Google Maps JavaScript API',
          'Google Geocoding API',
          'KG이니시스 API',
          '카카오 주소 검색 API',
          '카카오 로그인 API',
        ],
      },
      { label: '툴', item: ['Visual Studio Code', 'GitHub'] },
      { label: '서비스', item: ['Firebase', 'Netlify'] },
    ],
    demo: 'https://i-farm-6w2d.netlify.app/',
    source: 'https://github.com/yeon7513/smart-farm',
  },
];
