export const projectData = [
  {
    id: 'numberGuess',
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Number Guess',
    desc: '간단한 숫자 맞추기 게임입니다.\n1부터 9까지의 숫자 중 랜덤 숫자 3개를 맞추면 클리어 합니다.',
    period: '2024.05.10 - 2024.05.13',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows'] },
      { label: '라이브러리', item: [] },
      { label: '툴', item: ['Visual Studio Code'] },
      { label: '서비스', item: ['GitHub Pages'] },
    ],
    demo: 'https://yeon7513.github.io/number-guess/',
    source: 'https://github.com/yeon7513/number-guess',
  },
  {
    id: 'drinkMate',
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Drink Mate',
    desc: '자판기 머신을 구현했습니다.',
    period: '2024.07.12 - 2024.07.15',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows'] },
      { label: '라이브러리', item: [] },
      { label: '툴', item: ['Visual Studio Code'] },
      { label: '서비스', item: ['GitHub Pages'] },
    ],
    demo: 'https://yeon7513.github.io/vending-machine/',
    source: 'https://github.com/yeon7513/vending-machine',
  },
  {
    id: 'fakeKeyboard',
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Fake Keyboard',
    desc: 'key event를 활용한 가상 키보드입니다.',
    period: '2024.05.21 - 2024.05.21',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows'] },
      { label: '라이브러리', item: [] },
      { label: '툴', item: ['Visual Studio Code'] },
      { label: '서비스', item: ['GitHub Pages'] },
    ],
    demo: 'https://yeon7513.github.io/fake-keyboard/',
    source: 'https://github.com/yeon7513/fake-keyboard',
  },
  {
    id: 'todoList',
    imgUrl: 'https://picsum.photos/200/300',
    title: 'TODOLIST',
    desc: 'CRUD를 구현한 TODOLIST입니다.\n할 일과 할 시간을 생성하고, 수정 및 삭제가 가능합니다.',
    period: '2023.12.12 - 2023.12.14',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows', 'React JS'] },
      { label: '라이브러리', item: ['BootStrap'] },
      { label: '툴', item: ['Visual Studio Code'] },
      { label: '서비스', item: ['Netlify'] },
    ],
    demo: 'https://my-todolist-yeon.netlify.app/',
    source: 'https://github.com/yeon7513/my-todolist',
  },
  {
    id: 'matchCard',
    imgUrl: 'https://picsum.photos/200/300',
    title: "Let's Match Cards!",
    desc: '카드 짝 맞추기 게임입니다.',
    period: '2023.11.27. - 2023.12.12',
    techStack: [
      { label: '언어', item: ['HTML', 'CSS', 'JavaScript'] },
      { label: '환경', item: ['Windows', 'React JS'] },
      { label: '라이브러리', item: ['BootStrap'] },
      { label: '툴', item: ['Visual Studio Code'] },
      { label: '서비스', item: ['Netlify'] },
    ],
    demo: 'https://lets-match-cards.netlify.app/',
    source: 'https://github.com/yeon7513/macth-cards',
  },
];
